migrate(
  (app) => {
    const veiculosCol = app.findCollectionByNameOrId('veiculos')
    const empresas = app.findRecordsByFilter('empresas', '', '+created', 1, 0)
    if (empresas.length === 0) return
    const empresaId = empresas[0].id

    // 1. Remove previously seeded sample vehicles from 0010 (CAM-01, CAM-02, ESC-01, CAR-01, PERF-01)
    // Check if they are referenced in abastecimentos/manutencoes and remove those sample records first if needed
    try {
      const oldVehicles = app.findRecordsByFilter(
        'veiculos',
        `codigo_interno IN ('CAM-01', 'CAM-02', 'ESC-01', 'CAR-01', 'PERF-01')`,
        '',
        10,
        0,
      )
      for (const v of oldVehicles) {
        // Delete child abastecimentos / manutencoes linked to these sample vehicles
        app
          .db()
          .newQuery('DELETE FROM abastecimentos WHERE veiculo_id = {:vid}')
          .bind({ vid: v.id })
          .execute()
        app
          .db()
          .newQuery('DELETE FROM manutencoes WHERE veiculo_id = {:vid}')
          .bind({ vid: v.id })
          .execute()
        app.delete(v)
      }
    } catch (err) {
      console.log('Old vehicles cleanup note:', err)
    }

    // Real Fleet definition from official GC do Amaral Sertânia - ME / Pedreira document
    const realFleet = [
      // a) CENTRAL BRITAGEM (Produção estimada 1.200 m³/dia)
      {
        codigo_interno: 'CBR-ESC-01',
        placa: '',
        tipo: 'escavadeira',
        marca: 'Caterpillar',
        modelo: 'Escavadeira CAT 336',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 12450,
        km_atual: 0,
        horimetro_atual: 12450,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 1300000,
        setor: 'Central Britagem',
        observacoes:
          'Central de Britagem (1.200 m³/dia). Escavadeira hidráulica pesada para alimentação e praça.',
      },
      {
        codigo_interno: 'CBR-ESC-02',
        placa: '',
        tipo: 'escavadeira',
        marca: 'XCMG',
        modelo: 'Escavadeira XCMG XE370D',
        ano: 2021,
        tipo_medidor: 'ambos',
        medidor_atual: 6200,
        km_atual: 0,
        horimetro_atual: 6200,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 1400000,
        setor: 'Central Britagem',
        observacoes:
          'Central de Britagem. Escavadeira hidráulica 37t para desmonte e carregamento.',
      },
      {
        codigo_interno: 'CBR-ESC-03',
        placa: '',
        tipo: 'escavadeira',
        marca: 'New Holland',
        modelo: 'Escavadeira New Holland',
        ano: 2014,
        tipo_medidor: 'ambos',
        medidor_atual: 14100,
        km_atual: 0,
        horimetro_atual: 14100,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 350000,
        setor: 'Central Britagem',
        observacoes: 'Central de Britagem. Operação de apoio e movimentação de rochas.',
      },
      {
        codigo_interno: 'CBR-CAM-01',
        placa: '',
        tipo: 'caminhao',
        marca: 'Volkswagen',
        modelo: 'Caminhão VW 260 #1',
        ano: 2010,
        tipo_medidor: 'ambos',
        medidor_atual: 245000,
        km_atual: 245000,
        horimetro_atual: 9800,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 120000,
        setor: 'Central Britagem',
        observacoes: 'Central de Britagem. Transporte interno na praça de britagem.',
      },
      {
        codigo_interno: 'CBR-CAM-02',
        placa: '',
        tipo: 'caminhao',
        marca: 'Volkswagen',
        modelo: 'Caminhão VW 260 #2',
        ano: 2010,
        tipo_medidor: 'ambos',
        medidor_atual: 260000,
        km_atual: 260000,
        horimetro_atual: 10200,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 120000,
        setor: 'Central Britagem',
        observacoes: 'Central de Britagem. Transporte interno na praça de britagem.',
      },
      {
        codigo_interno: 'CBR-CAM-03',
        placa: '',
        tipo: 'caminhao',
        marca: 'Volkswagen',
        modelo: 'Caminhão VW 260 #3',
        ano: 2010,
        tipo_medidor: 'ambos',
        medidor_atual: 238000,
        km_atual: 238000,
        horimetro_atual: 9400,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 120000,
        setor: 'Central Britagem',
        observacoes: 'Central de Britagem. Transporte interno na praça de britagem.',
      },
      {
        codigo_interno: 'CBR-CAM-04',
        placa: '',
        tipo: 'caminhao',
        marca: 'Volkswagen',
        modelo: 'Caminhão VW 260 #4',
        ano: 2010,
        tipo_medidor: 'ambos',
        medidor_atual: 252000,
        km_atual: 252000,
        horimetro_atual: 9900,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 120000,
        setor: 'Central Britagem',
        observacoes: 'Central de Britagem. Transporte interno na praça de britagem.',
      },
      {
        codigo_interno: 'CBR-FE-01',
        placa: '',
        tipo: 'caminhao',
        marca: 'Sany',
        modelo: 'Sany Fora de Estrada SKT90S',
        ano: 2025,
        tipo_medidor: 'ambos',
        medidor_atual: 1850,
        km_atual: 1850,
        horimetro_atual: 1850,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 1320000,
        setor: 'Central Britagem',
        observacoes:
          'Central de Britagem. Caminhão fora-de-estrada para transporte pesado de rocha bruta da lavra ao britador.',
      },
      {
        codigo_interno: 'CBR-CAR-01',
        placa: 'PC24/CE',
        tipo: 'carregadeira',
        marca: 'Case',
        modelo: 'Pá Carregadeira Case 1021F',
        ano: 2018,
        tipo_medidor: 'ambos',
        medidor_atual: 7800,
        km_atual: 0,
        horimetro_atual: 7800,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 306000,
        setor: 'Central Britagem',
        observacoes: 'Central de Britagem. Carregamento pesado nos silos e baias de brita.',
      },
      {
        codigo_interno: 'CBR-CAR-02',
        placa: 'PC13/CE',
        tipo: 'carregadeira',
        marca: 'Case',
        modelo: 'Pá Carregadeira Case 821E',
        ano: 2016,
        tipo_medidor: 'ambos',
        medidor_atual: 9200,
        km_atual: 0,
        horimetro_atual: 9200,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 334676.04,
        setor: 'Central Britagem',
        observacoes: 'Central de Britagem. Movimentação de pilhas e alimentação de britadores.',
      },
      {
        codigo_interno: 'CBR-CAR-03',
        placa: '',
        tipo: 'carregadeira',
        marca: 'Michigan',
        modelo: 'Pá Carregadeira Michigan',
        ano: 2012,
        tipo_medidor: 'ambos',
        medidor_atual: 11500,
        km_atual: 0,
        horimetro_atual: 11500,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 600000,
        setor: 'Central Britagem',
        observacoes: 'Central de Britagem. Carregamento e apoio geral.',
      },
      {
        codigo_interno: 'CBR-CAR-04',
        placa: '',
        tipo: 'carregadeira',
        marca: 'Caterpillar',
        modelo: 'Pá Carregadeira CAT 930 930R',
        ano: 1985,
        tipo_medidor: 'ambos',
        medidor_atual: 18900,
        km_atual: 0,
        horimetro_atual: 18900,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 60000,
        setor: 'Central Britagem',
        observacoes: 'Central de Britagem. Carregadeira de reserva e apoio no pátio.',
      },

      // b) CARROS PARA ENTREGA DE BRITA (Caçambas Rodoviárias)
      {
        codigo_interno: 'ENT-CAC-01',
        placa: 'OEZ-4I27',
        tipo: 'caminhao',
        marca: 'Volkswagen',
        modelo: 'VW/24.250 CNC 6X2',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 312000,
        km_atual: 312000,
        horimetro_atual: 11200,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 250000,
        setor: 'Entrega de Brita',
        observacoes: 'Caçamba para entrega de brita e agregados.',
      },
      {
        codigo_interno: 'ENT-CAC-02',
        placa: 'QFF-2F62',
        tipo: 'caminhao',
        marca: 'Iveco',
        modelo: 'Iveco/Tector 240E28',
        ano: 2020,
        tipo_medidor: 'ambos',
        medidor_atual: 145000,
        km_atual: 145000,
        horimetro_atual: 5600,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 262292,
        setor: 'Entrega de Brita',
        observacoes: 'Caçamba para entrega de brita.',
      },
      {
        codigo_interno: 'ENT-CAC-03',
        placa: 'SKY-2H44',
        tipo: 'caminhao',
        marca: 'Mercedes-Benz',
        modelo: 'M.Benz/Atego 3330 K8X4CE',
        ano: 2023,
        tipo_medidor: 'ambos',
        medidor_atual: 62000,
        km_atual: 62000,
        horimetro_atual: 2400,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 500985,
        setor: 'Entrega de Brita',
        observacoes: 'Caçamba traçada 8x4 para entrega de agregados.',
      },
      {
        codigo_interno: 'ENT-CAC-04',
        placa: 'KHJ-2A42',
        tipo: 'caminhao',
        marca: 'Volkswagen',
        modelo: 'VW/31.320 CNC 6X4',
        ano: 2010,
        tipo_medidor: 'ambos',
        medidor_atual: 285000,
        km_atual: 285000,
        horimetro_atual: 11000,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 280000,
        setor: 'Entrega de Brita',
        observacoes: 'Caçamba traçada 6x4 para entrega de brita e pedra rachão.',
      },
      {
        codigo_interno: 'ENT-CAC-05',
        placa: 'TST-0I31',
        tipo: 'caminhao',
        marca: 'Volvo',
        modelo: 'Volvo/VM 290 6X4 R',
        ano: 2025,
        tipo_medidor: 'ambos',
        medidor_atual: 12000,
        km_atual: 12000,
        horimetro_atual: 450,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 700000,
        setor: 'Entrega de Brita',
        observacoes: 'Caçamba basculante pesada Volvo VM 290.',
      },
      {
        codigo_interno: 'ENT-CAC-06',
        placa: 'RLR-1B86',
        tipo: 'caminhao',
        marca: 'Iveco',
        modelo: 'Iveco/Tector 240E28',
        ano: 2022,
        tipo_medidor: 'ambos',
        medidor_atual: 89000,
        km_atual: 89000,
        horimetro_atual: 3400,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 301070,
        setor: 'Entrega de Brita',
        observacoes: 'Caçamba para entrega de brita.',
      },
      {
        codigo_interno: 'ENT-CAC-07',
        placa: 'TSX-2J58',
        tipo: 'caminhao',
        marca: 'Volvo',
        modelo: 'Volvo/VM 290 6X2 R',
        ano: 2026,
        tipo_medidor: 'ambos',
        medidor_atual: 5400,
        km_atual: 5400,
        horimetro_atual: 210,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 625000,
        setor: 'Entrega de Brita',
        observacoes: 'Caçamba basculante rodoviária Volvo 2026.',
      },
      {
        codigo_interno: 'ENT-CAC-08',
        placa: 'TSX-3A48',
        tipo: 'caminhao',
        marca: 'Volvo',
        modelo: 'Volvo/VM 290 6X4 R',
        ano: 2026,
        tipo_medidor: 'ambos',
        medidor_atual: 4800,
        km_atual: 4800,
        horimetro_atual: 190,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 705000,
        setor: 'Entrega de Brita',
        observacoes: 'Caçamba traçada 6x4 Volvo 2026.',
      },
      {
        codigo_interno: 'ENT-CAC-09',
        placa: 'TPA-2D27',
        tipo: 'caminhao',
        marca: 'Volvo',
        modelo: 'Volvo/VM 290 6X2 R',
        ano: 2025,
        tipo_medidor: 'ambos',
        medidor_atual: 18000,
        km_atual: 18000,
        horimetro_atual: 680,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 618944,
        setor: 'Entrega de Brita',
        observacoes: 'Caçamba basculante Volvo 2025.',
      },
      {
        codigo_interno: 'ENT-CAC-10',
        placa: 'BUD-7I74',
        tipo: 'caminhao',
        marca: 'Volkswagen',
        modelo: 'VW/31.320 CNC 6X4',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 278000,
        km_atual: 278000,
        horimetro_atual: 10800,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 300000,
        setor: 'Entrega de Brita',
        observacoes: 'Caçamba traçada VW para brita e rachão.',
      },

      // c) CENTRAL DE CONCRETO (Produção estimada 600 m³/dia)
      // Betoneiras:
      {
        codigo_interno: 'CNC-BET-01',
        placa: 'TPE-8A26',
        tipo: 'betoneira',
        marca: 'Volkswagen',
        modelo: 'VW/31.320 CRM 6X4 Betoneira',
        ano: 2025,
        tipo_medidor: 'ambos',
        medidor_atual: 14000,
        km_atual: 14000,
        horimetro_atual: 580,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 641900,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira 8m³.',
      },
      {
        codigo_interno: 'CNC-BET-02',
        placa: 'PFL-2E80',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 260 6X4 R Betoneira',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 215000,
        km_atual: 215000,
        horimetro_atual: 8200,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 221090,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-03',
        placa: 'PFJ-4C70',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 260 6X4 R Betoneira',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 228000,
        km_atual: 228000,
        horimetro_atual: 8600,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 221090,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-04',
        placa: 'PFJ-4C40',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 260 6X4 R Betoneira',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 222000,
        km_atual: 222000,
        horimetro_atual: 8400,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 221090,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-05',
        placa: 'SLF-1G92',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 290 6X4 R Betoneira',
        ano: 2024,
        tipo_medidor: 'ambos',
        medidor_atual: 24000,
        km_atual: 24000,
        horimetro_atual: 950,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 595500,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira moderna.',
      },
      {
        codigo_interno: 'CNC-BET-06',
        placa: 'PEG-6G21',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 260 6X4 R Betoneira',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 231000,
        km_atual: 231000,
        horimetro_atual: 8700,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 221090,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-07',
        placa: 'PEX-8A95',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 260 6X4 R Betoneira',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 219000,
        km_atual: 219000,
        horimetro_atual: 8300,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 221090,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-08',
        placa: 'SLF-1G52',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 290 6X4 R Betoneira',
        ano: 2024,
        tipo_medidor: 'ambos',
        medidor_atual: 26000,
        km_atual: 26000,
        horimetro_atual: 1020,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 595500,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-09',
        placa: 'TPE-8A06',
        tipo: 'betoneira',
        marca: 'Volkswagen',
        modelo: 'VW/31.320 CRM 6X4 Betoneira',
        ano: 2025,
        tipo_medidor: 'ambos',
        medidor_atual: 13500,
        km_atual: 13500,
        horimetro_atual: 540,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 641900,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-10',
        placa: 'PFD-6F23',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 260 6X4 R Betoneira',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 225000,
        km_atual: 225000,
        horimetro_atual: 8500,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 221090,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-11',
        placa: 'PEG-6E21',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 260 6X4 R Betoneira',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 218000,
        km_atual: 218000,
        horimetro_atual: 8250,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 221090,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-12',
        placa: 'PEX-8B15',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 260 6X4 R Betoneira',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 224000,
        km_atual: 224000,
        horimetro_atual: 8450,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 221090,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-13',
        placa: 'RLR-4F22',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 360 8X4 R Betoneira',
        ano: 2024,
        tipo_medidor: 'ambos',
        medidor_atual: 32000,
        km_atual: 32000,
        horimetro_atual: 1250,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 600000,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira pesada 8x4.',
      },
      {
        codigo_interno: 'CNC-BET-14',
        placa: 'RLR-4E62',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 360 8X4 R Betoneira',
        ano: 2024,
        tipo_medidor: 'ambos',
        medidor_atual: 31000,
        km_atual: 31000,
        horimetro_atual: 1200,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 600000,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira pesada 8x4.',
      },
      {
        codigo_interno: 'CNC-BET-15',
        placa: 'TSW-6F23',
        tipo: 'betoneira',
        marca: 'Volkswagen',
        modelo: 'VW/31.320 CRM 6X4 Betoneira',
        ano: 2027,
        tipo_medidor: 'ambos',
        medidor_atual: 1200,
        km_atual: 1200,
        horimetro_atual: 45,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 857430,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira nova geração.',
      },
      {
        codigo_interno: 'CNC-BET-16',
        placa: 'PFN-6A46',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 260 6X4 R Betoneira',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 229000,
        km_atual: 229000,
        horimetro_atual: 8650,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 221090,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-17',
        placa: 'PEP-1D25',
        tipo: 'betoneira',
        marca: 'Volvo',
        modelo: 'Volvo/VM 260 6X4 R Betoneira',
        ano: 2011,
        tipo_medidor: 'ambos',
        medidor_atual: 233000,
        km_atual: 233000,
        horimetro_atual: 8800,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 221090,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira.',
      },
      {
        codigo_interno: 'CNC-BET-18',
        placa: 'KJZ-1A76',
        tipo: 'betoneira',
        marca: 'Ford',
        modelo: 'Ford/Cargo 2622 E Betoneira',
        ano: 2009,
        tipo_medidor: 'ambos',
        medidor_atual: 310000,
        km_atual: 310000,
        horimetro_atual: 11800,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 103000,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira Cargo.',
      },
      {
        codigo_interno: 'CNC-BET-19',
        placa: 'TSW-6F54',
        tipo: 'betoneira',
        marca: 'Volkswagen',
        modelo: 'VW/31.320 CRM 6X4 Betoneira',
        ano: 2027,
        tipo_medidor: 'ambos',
        medidor_atual: 1100,
        km_atual: 1100,
        horimetro_atual: 42,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 857430,
        setor: 'Central de Concreto',
        observacoes: 'Central de Concreto. Caminhão betoneira nova geração.',
      },

      // Caminhões Pipa:
      {
        codigo_interno: 'CNC-PIP-01',
        placa: 'NPU-5A12',
        tipo: 'pipa',
        marca: 'Ford',
        modelo: 'Ford/Cargo 2422 CNL Caminhão Pipa',
        ano: 2012,
        tipo_medidor: 'ambos',
        medidor_atual: 195000,
        km_atual: 195000,
        horimetro_atual: 7500,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 244600,
        setor: 'Central de Concreto',
        observacoes: 'Caminhão pipa para umectação de vias e abastecimento de água.',
      },
      {
        codigo_interno: 'CNC-PIP-02',
        placa: 'ICJ-9361',
        tipo: 'pipa',
        marca: 'Mercedes-Benz',
        modelo: 'M.Benz/L 1113 Pipa',
        ano: 1980,
        tipo_medidor: 'ambos',
        medidor_atual: 340000,
        km_atual: 340000,
        horimetro_atual: 14000,
        combustivel_padrao: 'Diesel S500',
        status: 'ativo',
        valor_estimado: 45000,
        setor: 'Central de Concreto',
        observacoes: 'Caminhão pipa de suporte interno.',
      },
      {
        codigo_interno: 'CNC-PIP-03',
        placa: 'MNE-3229',
        tipo: 'pipa',
        marca: 'Volkswagen',
        modelo: 'VW/12.140 H Pipa',
        ano: 1996,
        tipo_medidor: 'ambos',
        medidor_atual: 290000,
        km_atual: 290000,
        horimetro_atual: 11200,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 48130,
        setor: 'Central de Concreto',
        observacoes: 'Caminhão pipa.',
      },
      {
        codigo_interno: 'CNC-PIP-04',
        placa: 'BTT-0D53',
        tipo: 'pipa',
        marca: 'Mercedes-Benz',
        modelo: 'M.Benz/L 2219 Pipa',
        ano: 1980,
        tipo_medidor: 'ambos',
        medidor_atual: 360000,
        km_atual: 360000,
        horimetro_atual: 14800,
        combustivel_padrao: 'Diesel S500',
        status: 'ativo',
        valor_estimado: 45130,
        setor: 'Central de Concreto',
        observacoes: 'Caminhão pipa para apoio a usina de concreto.',
      },

      // Bombas de Concreto:
      {
        codigo_interno: 'CNC-BOM-01',
        placa: 'OSI-8I50',
        tipo: 'bomba',
        marca: 'Ford',
        modelo: 'Bomba Ford/Cargo 1319',
        ano: 2014,
        tipo_medidor: 'ambos',
        medidor_atual: 142000,
        km_atual: 142000,
        horimetro_atual: 4800,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 211458,
        setor: 'Central de Concreto',
        observacoes: 'Caminhão bomba estacionária de concreto.',
      },
      {
        codigo_interno: 'CNC-BOM-02',
        placa: 'CBL-8A74',
        tipo: 'bomba',
        marca: 'Volkswagen',
        modelo: 'Bomba VW/16.170 BT',
        ano: 1995,
        tipo_medidor: 'ambos',
        medidor_atual: 298000,
        km_atual: 298000,
        horimetro_atual: 9800,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 50000,
        setor: 'Central de Concreto',
        observacoes: 'Bomba de concreto acoplada.',
      },
      {
        codigo_interno: 'CNC-BOM-03',
        placa: 'EBY-3875',
        tipo: 'bomba',
        marca: 'Ford',
        modelo: 'Caminhão Bomba Ford/Cargo 1517E',
        ano: 2008,
        tipo_medidor: 'ambos',
        medidor_atual: 210000,
        km_atual: 210000,
        horimetro_atual: 6900,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 105000,
        setor: 'Central de Concreto',
        observacoes: 'Bomba de concreto para bombeamento de lajes e obras.',
      },
      {
        codigo_interno: 'CNC-BOM-04',
        placa: 'HXH-2H81',
        tipo: 'bomba',
        marca: 'Mercedes-Benz',
        modelo: 'Caminhão Bomba M.Benz/710',
        ano: 2005,
        tipo_medidor: 'ambos',
        medidor_atual: 185000,
        km_atual: 185000,
        horimetro_atual: 6100,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 126298,
        setor: 'Central de Concreto',
        observacoes: 'Bomba de concreto ágil para centros urbanos.',
      },
      {
        codigo_interno: 'CNC-BOM-05',
        placa: 'QLM-7C12',
        tipo: 'bomba',
        marca: 'Volkswagen',
        modelo: 'Bomba VW/15.190 CRM 4X2 4P',
        ano: 2017,
        tipo_medidor: 'ambos',
        medidor_atual: 110000,
        km_atual: 110000,
        horimetro_atual: 3900,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 221000,
        setor: 'Central de Concreto',
        observacoes: 'Bomba de concreto 2017/2018 cabine estendida.',
      },
      {
        codigo_interno: 'CNC-BOM-06',
        placa: 'NEP-9J29',
        tipo: 'bomba',
        marca: 'Mercedes-Benz',
        modelo: 'Bomba M.Benz/710',
        ano: 2008,
        tipo_medidor: 'ambos',
        medidor_atual: 172000,
        km_atual: 172000,
        horimetro_atual: 5600,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 145372,
        setor: 'Central de Concreto',
        observacoes: 'Bomba de concreto rebocada montada em chassi.',
      },

      // Pás Carregadeiras da Central de Concreto:
      {
        codigo_interno: 'CNC-CAR-01',
        placa: '',
        tipo: 'carregadeira',
        marca: 'Komatsu',
        modelo: 'Pá Carregadeira WA320-5 Komatsu',
        ano: 2015,
        tipo_medidor: 'ambos',
        medidor_atual: 8400,
        km_atual: 0,
        horimetro_atual: 8400,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 240000,
        setor: 'Central de Concreto',
        observacoes: 'Série B10443 Komatsu. Alimentação dos agregados da usina de concreto.',
      },
      {
        codigo_interno: 'CNC-CAR-02',
        placa: '',
        tipo: 'carregadeira',
        marca: 'ZL',
        modelo: 'Pá Carregadeira ZL30H',
        ano: 2017,
        tipo_medidor: 'ambos',
        medidor_atual: 6900,
        km_atual: 0,
        horimetro_atual: 6900,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 230000,
        setor: 'Central de Concreto',
        observacoes: 'Alimentação de areia e brita na usina.',
      },
      {
        codigo_interno: 'CNC-CAR-03',
        placa: '',
        tipo: 'carregadeira',
        marca: 'ZL',
        modelo: 'Pá Carregadeira ZL30G',
        ano: 2016,
        tipo_medidor: 'ambos',
        medidor_atual: 7300,
        km_atual: 0,
        horimetro_atual: 7300,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 230000,
        setor: 'Central de Concreto',
        observacoes: 'Movimentação de agregados.',
      },
      {
        codigo_interno: 'CNC-CAR-04',
        placa: '',
        tipo: 'carregadeira',
        marca: 'Hyundai',
        modelo: 'Carregadeira Hyundai HL740-7A',
        ano: 2012,
        tipo_medidor: 'ambos',
        medidor_atual: 10400,
        km_atual: 0,
        horimetro_atual: 10400,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 280000,
        setor: 'Central de Concreto',
        observacoes: 'Pá carregadeira média para centrais de concreto.',
      },

      // Centrais de Concreto Fixo/Filiais:
      {
        codigo_interno: 'CNC-USI-01',
        placa: '',
        tipo: 'central_concreto',
        marca: 'Usina Fixa',
        modelo: 'Central de Concreto Monteiro-PB',
        ano: 2018,
        tipo_medidor: 'horas',
        medidor_atual: 5400,
        km_atual: 0,
        horimetro_atual: 5400,
        combustivel_padrao: 'Eletrico',
        status: 'ativo',
        valor_estimado: 1200000,
        setor: 'Central de Concreto',
        observacoes: 'Unidade de dosagem e usinagem de concreto em Monteiro-PB.',
      },
      {
        codigo_interno: 'CNC-USI-02',
        placa: '',
        tipo: 'central_concreto',
        marca: 'Usina Fixa',
        modelo: 'Central de Concreto São José do Egito-PE',
        ano: 2019,
        tipo_medidor: 'horas',
        medidor_atual: 4900,
        km_atual: 0,
        horimetro_atual: 4900,
        combustivel_padrao: 'Eletrico',
        status: 'ativo',
        valor_estimado: 1000000,
        setor: 'Central de Concreto',
        observacoes: 'Unidade de concreto dosado em São José do Egito-PE.',
      },
      {
        codigo_interno: 'CNC-USI-03',
        placa: '',
        tipo: 'central_concreto',
        marca: 'Usina Fixa',
        modelo: 'Central de Concreto Caicó-RN',
        ano: 2019,
        tipo_medidor: 'horas',
        medidor_atual: 5100,
        km_atual: 0,
        horimetro_atual: 5100,
        combustivel_padrao: 'Eletrico',
        status: 'ativo',
        valor_estimado: 1000000,
        setor: 'Central de Concreto',
        observacoes: 'Unidade de concreto dosado em Caicó-RN.',
      },
      {
        codigo_interno: 'CNC-USI-04',
        placa: '',
        tipo: 'central_concreto',
        marca: 'Usina Fixa',
        modelo: 'Central de Concreto Santa Luzia-PB',
        ano: 2020,
        tipo_medidor: 'horas',
        medidor_atual: 3600,
        km_atual: 0,
        horimetro_atual: 3600,
        combustivel_padrao: 'Eletrico',
        status: 'ativo',
        valor_estimado: 500000,
        setor: 'Central de Concreto',
        observacoes: 'Unidade de concreto dosado em Santa Luzia-PB.',
      },
      {
        codigo_interno: 'CNC-USI-05',
        placa: '',
        tipo: 'central_concreto',
        marca: 'Usina Fixa',
        modelo: 'Central de Concreto Patos-PB',
        ano: 2021,
        tipo_medidor: 'horas',
        medidor_atual: 4200,
        km_atual: 0,
        horimetro_atual: 4200,
        combustivel_padrao: 'Eletrico',
        status: 'ativo',
        valor_estimado: 1500000,
        setor: 'Central de Concreto',
        observacoes: 'Principal usina dosadora de concreto em Patos-PB.',
      },

      // d) CENTRAL DE BRITAGEM LOKOTRACK (Produção estimada 1.500 m³/dia)
      {
        codigo_interno: 'LOK-ESC-01',
        placa: '',
        tipo: 'escavadeira',
        marca: 'John Deere',
        modelo: 'Escavadeira John Deere 210 #1',
        ano: 2018,
        tipo_medidor: 'ambos',
        medidor_atual: 8200,
        km_atual: 0,
        horimetro_atual: 8200,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 520000,
        setor: 'Central Britagem Lokotrack',
        observacoes: 'Alimentação direta da planta móvel Lokotrack (1.500 m³/dia).',
      },
      {
        codigo_interno: 'LOK-ESC-02',
        placa: '',
        tipo: 'escavadeira',
        marca: 'John Deere',
        modelo: 'Escavadeira John Deere 210 #2',
        ano: 2019,
        tipo_medidor: 'ambos',
        medidor_atual: 7600,
        km_atual: 0,
        horimetro_atual: 7600,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 520000,
        setor: 'Central Britagem Lokotrack',
        observacoes: 'Alimentação direta e desmonte no marroeiro Lokotrack.',
      },
      {
        codigo_interno: 'LOK-ESC-03',
        placa: '',
        tipo: 'escavadeira',
        marca: 'Caterpillar',
        modelo: 'Escavadeira CAT 336',
        ano: 2025,
        tipo_medidor: 'ambos',
        medidor_atual: 1100,
        km_atual: 0,
        horimetro_atual: 1100,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 1310000,
        setor: 'Central Britagem Lokotrack',
        observacoes: 'Escavadeira CAT 336 2025 de alta capacidade na britagem móvel.',
      },
      {
        codigo_interno: 'LOK-CAR-01',
        placa: '',
        tipo: 'carregadeira',
        marca: 'M',
        modelo: 'Pá Carregadeira M 100HD',
        ano: 2017,
        tipo_medidor: 'ambos',
        medidor_atual: 7900,
        km_atual: 0,
        horimetro_atual: 7900,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 600000,
        setor: 'Central Britagem Lokotrack',
        observacoes:
          'Pá carregadeira pesada para carregamento de britas produzidas pelo Lokotrack.',
      },
      {
        codigo_interno: 'LOK-BRIT-01',
        placa: '',
        tipo: 'britador',
        marca: 'Metso Outotec',
        modelo: 'Lokotrack Nº 1 LT 106 Marroeiro',
        ano: 2024,
        tipo_medidor: 'horas',
        medidor_atual: 1850,
        km_atual: 0,
        horimetro_atual: 1850,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 3756887.75,
        setor: 'Central Britagem Lokotrack',
        observacoes: 'Britador de mandíbulas móvel sobre esteiras Lokotrack LT106 marroeiro 2024.',
      },
      {
        codigo_interno: 'LOK-BRIT-02',
        placa: '',
        tipo: 'britador',
        marca: 'Metso Outotec',
        modelo: 'Lokotrack Nº 2 LT 106 Marroeiro',
        ano: 2012,
        tipo_medidor: 'horas',
        medidor_atual: 14800,
        km_atual: 0,
        horimetro_atual: 14800,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 4062051.01,
        setor: 'Central Britagem Lokotrack',
        observacoes: 'Britador de mandíbulas móvel sobre esteiras Lokotrack LT106 marroeiro 2012.',
      },
      {
        codigo_interno: 'LOK-BRIT-03',
        placa: '',
        tipo: 'britador',
        marca: 'Metso Outotec',
        modelo: 'Lokotrack Nº 3 LT 106 Marroeiro',
        ano: 2012,
        tipo_medidor: 'horas',
        medidor_atual: 15400,
        km_atual: 0,
        horimetro_atual: 15400,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 2000000,
        setor: 'Central Britagem Lokotrack',
        observacoes: 'Britador móvel sobre esteiras Lokotrack LT106 marroeiro 2012.',
      },
      {
        codigo_interno: 'LOK-BRIT-04',
        placa: '',
        tipo: 'britador',
        marca: 'Metso Outotec',
        modelo: 'Lokotrack Nº 4 LT 200 Cone',
        ano: 2012,
        tipo_medidor: 'horas',
        medidor_atual: 16100,
        km_atual: 0,
        horimetro_atual: 16100,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 2000000,
        setor: 'Central Britagem Lokotrack',
        observacoes:
          'Britador móvel cônico sobre esteiras Lokotrack LT 200 Cone para britagem secundária/terciária.',
      },
      {
        codigo_interno: 'LOK-PEN-01',
        placa: '',
        tipo: 'peneira',
        marca: 'Astec',
        modelo: 'Lokotrack Nº 5 Astec Peneira',
        ano: 2012,
        tipo_medidor: 'horas',
        medidor_atual: 15800,
        km_atual: 0,
        horimetro_atual: 15800,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 2000000,
        setor: 'Central Britagem Lokotrack',
        observacoes:
          'Peneira classificadora móvel sobre esteiras Astec para separação de Brita 12, Brita 19, rachão e pó de pedra.',
      },

      // e) CARROS E MOTOS DE ENGENHEIROS / ENCARREGADOS
      {
        codigo_interno: 'ENG-AUT-01',
        placa: 'QSD-6E44',
        tipo: 'carro_passeio',
        marca: 'Toyota',
        modelo: 'Toyota Hilux CDSRXA4FD',
        ano: 2019,
        tipo_medidor: 'ambos',
        medidor_atual: 118000,
        km_atual: 118000,
        horimetro_atual: 3200,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 162065,
        setor: 'Engenharia / Supervisão',
        observacoes: 'Caminhonete 4x4 da engenharia de campo e supervisão de lavra.',
      },
      {
        codigo_interno: 'ENG-MOT-01',
        placa: 'NQE-0H26',
        tipo: 'moto',
        marca: 'Honda',
        modelo: 'Honda Pop 100',
        ano: 2010,
        tipo_medidor: 'ambos',
        medidor_atual: 42000,
        km_atual: 42000,
        horimetro_atual: 1200,
        combustivel_padrao: 'Gasolina',
        status: 'ativo',
        valor_estimado: 6324,
        setor: 'Engenharia / Supervisão',
        observacoes: 'Motocicleta para rondas internas rápidas na pedreira.',
      },
      {
        codigo_interno: 'ENG-AUT-02',
        placa: 'RZW-9F79',
        tipo: 'carro_passeio',
        marca: 'Fiat',
        modelo: 'Fiat Mobi Like',
        ano: 2022,
        tipo_medidor: 'ambos',
        medidor_atual: 48000,
        km_atual: 48000,
        horimetro_atual: 1400,
        combustivel_padrao: 'Etanol',
        status: 'ativo',
        valor_estimado: 53348,
        setor: 'Engenharia / Supervisão',
        observacoes: 'Carro de apoio administrativo e encarregados.',
      },
      {
        codigo_interno: 'ENG-AUT-03',
        placa: 'QFX-0J32',
        tipo: 'carro_passeio',
        marca: 'Toyota',
        modelo: 'Toyota Hilux CDSRVA4FD',
        ano: 2022,
        tipo_medidor: 'ambos',
        medidor_atual: 56000,
        km_atual: 56000,
        horimetro_atual: 1800,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 230000,
        setor: 'Engenharia / Supervisão',
        observacoes: 'Caminhonete 4x4 do engenheiro residente.',
      },
      {
        codigo_interno: 'ENG-AUT-04',
        placa: 'RMZ-3G56',
        tipo: 'carro_passeio',
        marca: 'Volkswagen',
        modelo: 'VW Saveiro TL MBVS',
        ano: 2021,
        tipo_medidor: 'ambos',
        medidor_atual: 74000,
        km_atual: 74000,
        horimetro_atual: 2200,
        combustivel_padrao: 'Gasolina',
        status: 'ativo',
        valor_estimado: 72155,
        setor: 'Engenharia / Supervisão',
        observacoes: 'Utilitário saveiro para encarregado de manutenção e peças.',
      },
      {
        codigo_interno: 'ENG-AUT-05',
        placa: 'BLJ-9D83',
        tipo: 'carro_passeio',
        marca: 'Chevrolet',
        modelo: 'GM D20 Custom S',
        ano: 1995,
        tipo_medidor: 'ambos',
        medidor_atual: 320000,
        km_atual: 320000,
        horimetro_atual: 11000,
        combustivel_padrao: 'Diesel S500',
        status: 'ativo',
        valor_estimado: 76600,
        setor: 'Engenharia / Supervisão',
        observacoes: 'Camionete diesel reforçada de suporte mecânico e campo.',
      },
      {
        codigo_interno: 'ENG-AUT-06',
        placa: 'NQG-8A12',
        tipo: 'carro_passeio',
        marca: 'Ford',
        modelo: 'Ford Ranger XLS CS4M32',
        ano: 2014,
        tipo_medidor: 'ambos',
        medidor_atual: 168000,
        km_atual: 168000,
        horimetro_atual: 4900,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 71000,
        setor: 'Engenharia / Supervisão',
        observacoes: 'Caminhonete cabine simples para suporte na lavra.',
      },
      {
        codigo_interno: 'ENG-AUT-07',
        placa: 'RLV-9J83',
        tipo: 'carro_passeio',
        marca: 'Toyota',
        modelo: 'Toyota Hilux SW4 SWDMDA4MD',
        ano: 2022,
        tipo_medidor: 'ambos',
        medidor_atual: 52000,
        km_atual: 52000,
        horimetro_atual: 1600,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 334779,
        setor: 'Engenharia / Supervisão',
        observacoes: 'Veículo executivo da diretoria e gerência geral.',
      },
      {
        codigo_interno: 'ENG-AUT-08',
        placa: 'TOZ-2D08',
        tipo: 'carro_passeio',
        marca: 'Nissan',
        modelo: 'Nissan Frontier',
        ano: 2025,
        tipo_medidor: 'ambos',
        medidor_atual: 15000,
        km_atual: 15000,
        horimetro_atual: 520,
        combustivel_padrao: 'Diesel S10',
        status: 'ativo',
        valor_estimado: 230000,
        setor: 'Engenharia / Supervisão',
        observacoes: 'Caminhonete 4x4 da equipe técnica e fiscalização de obras.',
      },
      {
        codigo_interno: 'ENG-AUT-09',
        placa: 'QNO-2F73',
        tipo: 'carro_passeio',
        marca: 'Fiat',
        modelo: 'Fiat Strada HD WK CE E',
        ano: 2018,
        tipo_medidor: 'ambos',
        medidor_atual: 98000,
        km_atual: 98000,
        horimetro_atual: 2900,
        combustivel_padrao: 'Gasolina',
        status: 'ativo',
        valor_estimado: 68000,
        setor: 'Engenharia / Supervisão',
        observacoes: 'Utilitário strada para encarregado de britagem.',
      },
      {
        codigo_interno: 'ENG-AUT-10',
        placa: 'QFA-0I61',
        tipo: 'carro_passeio',
        marca: 'Volkswagen',
        modelo: 'VW Saveiro RB MBVS',
        ano: 2020,
        tipo_medidor: 'ambos',
        medidor_atual: 82000,
        km_atual: 82000,
        horimetro_atual: 2500,
        combustivel_padrao: 'Gasolina',
        status: 'ativo',
        valor_estimado: 79000,
        setor: 'Engenharia / Supervisão',
        observacoes: 'Utilitário saveiro para suporte de campo e manutenção.',
      },
    ]

    for (const item of realFleet) {
      try {
        const existing = app.findRecordsByFilter(
          'veiculos',
          `empresa_id = '${empresaId}' && codigo_interno = '${item.codigo_interno}'`,
          '',
          1,
          0,
        )
        if (existing.length > 0) {
          const rec = existing[0]
          rec.set('modelo', item.modelo)
          rec.set('marca', item.marca)
          rec.set('placa', item.placa || '')
          rec.set('tipo', item.tipo)
          rec.set('ano', item.ano)
          rec.set('tipo_medidor', item.tipo_medidor)
          rec.set('medidor_atual', item.medidor_atual)
          rec.set('km_atual', item.km_atual)
          rec.set('horimetro_atual', item.horimetro_atual)
          rec.set('combustivel_padrao', item.combustivel_padrao)
          rec.set('status', item.status)
          rec.set('setor', item.setor)
          rec.set('valor_estimado', item.valor_estimado)
          rec.set('observacoes', item.observacoes)
          app.save(rec)
          continue
        }
      } catch (_) {}

      const rec = new Record(veiculosCol)
      rec.set('empresa_id', empresaId)
      rec.set('codigo_interno', item.codigo_interno)
      rec.set('placa', item.placa || '')
      rec.set('tipo', item.tipo)
      rec.set('marca', item.marca)
      rec.set('modelo', item.modelo)
      rec.set('ano', item.ano)
      rec.set('tipo_medidor', item.tipo_medidor)
      rec.set('medidor_atual', item.medidor_atual)
      rec.set('km_atual', item.km_atual)
      rec.set('horimetro_atual', item.horimetro_atual)
      rec.set('combustivel_padrao', item.combustivel_padrao)
      rec.set('status', item.status)
      rec.set('setor', item.setor)
      rec.set('valor_estimado', item.valor_estimado)
      rec.set('observacoes', item.observacoes)
      app.save(rec)
    }
  },
  (app) => {
    // down: remove seeded vehicles with prefixes CBR, ENT, CNC, LOK, ENG
    try {
      app
        .db()
        .newQuery(
          "DELETE FROM veiculos WHERE codigo_interno LIKE 'CBR-%' OR codigo_interno LIKE 'ENT-%' OR codigo_interno LIKE 'CNC-%' OR codigo_interno LIKE 'LOK-%' OR codigo_interno LIKE 'ENG-%'",
        )
        .execute()
    } catch (_) {}
  },
)
